### PR TITLE
Update lowercase-keys to v2 and drop support for node<8

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
To completely dedupe it in `cacheable-request`.  It'll require a major version bump here, though, to drop `node<8`.

### CODE REVIEW

**Comment by lukechilds** [comment]
@wtgtybhertgeghgtwtg I'm happy dropping support for Node.js <8.

If you update .travis.yml I'm happy to merge this and publish a new major version.

**Comment by wtgtybhertgeghgtwtg** [comment]
I used the `.travis.yml` from `cacheable-request` as a reference.  Is this range acceptable?

**Comment by lukechilds** [comment]
@wtgtybhertgeghgtwtg perfect ❤️

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you for merging.

**Comment by lukechilds** [comment]
@wtgtybhertgeghgtwtg published on npm `responselike@2.0.0`.

**Comment by wtgtybhertgeghgtwtg** [comment]
For the intended effect to occur, https://github.com/lukechilds/cacheable-request/pull/90 must be merged.  Is there something I can do to help with that?

**Comment by lukechilds** [comment]
@wtgtybhertgeghgtwtg done and published `cacheable-request@7.0.0`.

**Pull request merged**
